<a href="https://colab.research.google.com/github/Yuvrajtakk/PYTHON/blob/master/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [36]:
data = {
    "Name": ["Alice", "Bob", "Charlie", np.nan, "Eve", "Frank", "Grace", "Heidi", "Ivan", "Judy"],
    "Age": [25, 32, np.nan, 45, 29, 34, np.nan, 41, 30, 27],
    "Gender": ["Female", "Male", "Male", "male", np.nan, "female", "Female", "Male", "Male", "Female"],
    "Income": [50000, 60000, 55000, 45000, np.nan, 70000, 52000, 48000, 62000, 50000],
    "City": ["New York", "Los Angeles", "New York", "Chicago", "Los Angeles", np.nan, "Chicago", "New York", "Chicago", "Chicago"],
    "Has_Debt": ["Yes", "No", "Yes", "No", "Yes", "Yes", "No", np.nan, "Yes", "No"],
    "Debt_Amount": [15000, 0, 12000, 0, 18000, 20000, 0, 14000, np.nan, 0]
}

In [37]:
df = pd.DataFrame(data)

In [38]:

df

      Name   Age  Gender   Income         City Has_Debt  Debt_Amount
0    Alice  25.0  Female  50000.0     New York      Yes      15000.0
1      Bob  32.0    Male  60000.0  Los Angeles       No          0.0
2  Charlie   NaN    Male  55000.0     New York      Yes      12000.0
3      NaN  45.0    male  45000.0      Chicago       No          0.0
4      Eve  29.0     NaN      NaN  Los Angeles      Yes      18000.0
5    Frank  34.0  female  70000.0          NaN      Yes      20000.0
6    Grace   NaN  Female  52000.0      Chicago       No          0.0
7    Heidi  41.0    Male  48000.0     New York      NaN      14000.0
8     Ivan  30.0    Male  62000.0      Chicago      Yes          NaN
9     Judy  27.0  Female  50000.0      Chicago       No          0.0

In [39]:
print(df)

      Name   Age  Gender   Income         City Has_Debt  Debt_Amount
0    Alice  25.0  Female  50000.0     New York      Yes      15000.0
1      Bob  32.0    Male  60000.0  Los Angeles       No          0.0
2  Charlie   NaN    Male  55000.0     New York      Yes      12000.0
3      NaN  45.0    male  45000.0      Chicago       No          0.0
4      Eve  29.0     NaN      NaN  Los Angeles      Yes      18000.0
5    Frank  34.0  female  70000.0          NaN      Yes      20000.0
6    Grace   NaN  Female  52000.0      Chicago       No          0.0
7    Heidi  41.0    Male  48000.0     New York      NaN      14000.0
8     Ivan  30.0    Male  62000.0      Chicago      Yes          NaN
9     Judy  27.0  Female  50000.0      Chicago       No          0.0

In [40]:

df.head(7)

      Name   Age  Gender   Income         City Has_Debt  Debt_Amount
0    Alice  25.0  Female  50000.0     New York      Yes      15000.0
1      Bob  32.0    Male  60000.0  Los Angeles       No          0.0
2  Charlie   NaN    Male  55000.0     New York      Yes      12000.0
3      NaN  45.0    male  45000.0      Chicago       No          0.0
4      Eve  29.0     NaN      NaN  Los Angeles      Yes      18000.0
5    Frank  34.0  female  70000.0          NaN      Yes      20000.0
6    Grace   NaN  Female  52000.0      Chicago       No          0.0

In [41]:
df.tail(3)

    Name   Age  Gender   Income      City Has_Debt  Debt_Amount
7  Heidi  41.0    Male  48000.0  New York      NaN      14000.0
8   Ivan  30.0    Male  62000.0   Chicago      Yes          NaN
9   Judy  27.0  Female  50000.0   Chicago       No          0.0

In [42]:
df.describe()

             Age        Income   Debt_Amount
count   8.000000      9.000000      9.000000
mean   32.875000  54666.666667   8777.777778
std     6.916595   7952.986860   8628.119404
min    25.000000  45000.000000      0.000000
25%    28.500000  50000.000000      0.000000
50%    31.000000  52000.000000  12000.000000
75%    35.750000  60000.000000  15000.000000
max    45.000000  70000.000000  20000.000000

In [43]:
df.describe(include= 'all')

         Name        Age Gender        Income     City Has_Debt   Debt_Amount
count       9   8.000000      9      9.000000        9        9      9.000000
unique      9        NaN      4           NaN        3        2           NaN
top     Alice        NaN   Male           NaN  Chicago      Yes           NaN
freq        1        NaN      4           NaN        4        5           NaN
mean      NaN  32.875000    NaN  54666.666667      NaN      NaN   8777.777778
std       NaN   6.916595    NaN   7952.986860      NaN      NaN   8628.119404
min       NaN  25.000000    NaN  45000.000000      NaN      NaN      0.000000
25%       NaN  28.500000    NaN  50000.000000      NaN      NaN      0.000000
50%       NaN  31.000000    NaN  52000.000000      NaN      NaN  12000.000000
75%       NaN  35.750000    NaN  60000.000000      NaN      NaN  15000.000000
max       NaN  45.000000    NaN  70000.000000      NaN      NaN  20000.000000

In [44]:
df.isnull().sum()

Name           1
Age            2
Gender         1
Income         1
City           1
Has_Debt       1
Debt_Amount    1
dtype: int64

In [50]:
df['Name'] = df['Name'].fillna('Unknown')

In [51]:
df

      Name   Age  Gender   Income         City Has_Debt  Debt_Amount     name
0    Alice  25.0  Female  50000.0     New York      Yes      15000.0    Alice
1      Bob  32.0    Male  60000.0  Los Angeles       No          0.0      Bob
2  Charlie  31.0    Male  55000.0     New York      Yes      12000.0  Charlie
3  Unknown  45.0    male  45000.0      Chicago       No          0.0  Unknown
4      Eve  29.0     NaN      NaN  Los Angeles      Yes      18000.0      Eve
5    Frank  34.0  female  70000.0          NaN      Yes      20000.0    Frank
6    Grace  31.0  Female  52000.0      Chicago       No          0.0    Grace
7    Heidi  41.0    Male  48000.0     New York      NaN      14000.0    Heidi
8     Ivan  30.0    Male  62000.0      Chicago      Yes          NaN     Ivan
9     Judy  27.0  Female  50000.0      Chicago       No          0.0     Judy

In [52]:
df

      Name   Age  Gender   Income         City Has_Debt  Debt_Amount     name
0    Alice  25.0  Female  50000.0     New York      Yes      15000.0    Alice
1      Bob  32.0    Male  60000.0  Los Angeles       No          0.0      Bob
2  Charlie  31.0    Male  55000.0     New York      Yes      12000.0  Charlie
3  Unknown  45.0    male  45000.0      Chicago       No          0.0  Unknown
4      Eve  29.0     NaN      NaN  Los Angeles      Yes      18000.0      Eve
5    Frank  34.0  female  70000.0          NaN      Yes      20000.0    Frank
6    Grace  31.0  Female  52000.0      Chicago       No          0.0    Grace
7    Heidi  41.0    Male  48000.0     New York      NaN      14000.0    Heidi
8     Ivan  30.0    Male  62000.0      Chicago      Yes          NaN     Ivan
9     Judy  27.0  Female  50000.0      Chicago       No          0.0     Judy

In [53]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [54]:
df

      Name   Age  Gender   Income         City Has_Debt  Debt_Amount     name
0    Alice  25.0  Female  50000.0     New York      Yes      15000.0    Alice
1      Bob  32.0    Male  60000.0  Los Angeles       No          0.0      Bob
2  Charlie  31.0    Male  55000.0     New York      Yes      12000.0  Charlie
3  Unknown  45.0    male  45000.0      Chicago       No          0.0  Unknown
4      Eve  29.0     NaN      NaN  Los Angeles      Yes      18000.0      Eve
5    Frank  34.0  female  70000.0          NaN      Yes      20000.0    Frank
6    Grace  31.0  Female  52000.0      Chicago       No          0.0    Grace
7    Heidi  41.0    Male  48000.0     New York      NaN      14000.0    Heidi
8     Ivan  30.0    Male  62000.0      Chicago      Yes          NaN     Ivan
9     Judy  27.0  Female  50000.0      Chicago       No          0.0     Judy

In [55]:
df['Income'] = df['Income'].fillna(df['Income'].mean())
df

,Name,Age,Gender,Income,City,Has_Debt,Debt_Amount,name
0,Alice,25.0,Female,50000.000000,New York,Yes,15000.0,Alice
1,Bob,32.0,Male,60000.000000,Los Angeles,No,0.0,Bob
2,Charlie,31.0,Male,55000.000000,New York,Yes,12000.0,Charlie
3,Unknown,45.0,male,45000.000000,Chicago,No,0.0,Unknown
4,Eve,29.0,NaN,54666.666667,Los Angeles,Yes,18000.0,Eve
5,Frank,34.0,female,70000.000000,NaN,Yes,20000.0,Frank
6,Grace,31.0,Female,52000.000000,Chicago,No,0.0,Grace
7,Heidi,41.0,Male,48000.000000,New York,NaN,14000.0,Heidi
8,Ivan,30.0,Male,62000.000000,Chicago,Yes,NaN,Ivan
9,Judy,27.0,Female,50000.000000,Chicago,No,0.0,Judy

In [56]:
#gender
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df

,Name,Age,Gender,Income,City,Has_Debt,Debt_Amount,name
0,Alice,25.0,Female,50000.000000,New York,Yes,15000.0,Alice
1,Bob,32.0,Male,60000.000000,Los Angeles,No,0.0,Bob
2,Charlie,31.0,Male,55000.000000,New York,Yes,12000.0,Charlie
3,Unknown,45.0,male,45000.000000,Chicago,No,0.0,Unknown
4,Eve,29.0,Male,54666.666667,Los Angeles,Yes,18000.0,Eve
5,Frank,34.0,female,70000.000000,NaN,Yes,20000.0,Frank
6,Grace,31.0,Female,52000.000000,Chicago,No,0.0,Grace
7,Heidi,41.0,Male,48000.000000,New York,NaN,14000.0,Heidi
8,Ivan,30.0,Male,62000.000000,Chicago,Yes,NaN,Ivan
9,Judy,27.0,Female,50000.000000,Chicago,No,0.0,Judy

In [57]:
#city

df['City'] = df['City'].ffill()
df

,Name,Age,Gender,Income,City,Has_Debt,Debt_Amount,name
0,Alice,25.0,Female,50000.000000,New York,Yes,15000.0,Alice
1,Bob,32.0,Male,60000.000000,Los Angeles,No,0.0,Bob
2,Charlie,31.0,Male,55000.000000,New York,Yes,12000.0,Charlie
3,Unknown,45.0,male,45000.000000,Chicago,No,0.0,Unknown
4,Eve,29.0,Male,54666.666667,Los Angeles,Yes,18000.0,Eve
5,Frank,34.0,female,70000.000000,Los Angeles,Yes,20000.0,Frank
6,Grace,31.0,Female,52000.000000,Chicago,No,0.0,Grace
7,Heidi,41.0,Male,48000.000000,New York,NaN,14000.0,Heidi
8,Ivan,30.0,Male,62000.000000,Chicago,Yes,NaN,Ivan
9,Judy,27.0,Female,50000.000000,Chicago,No,0.0,Judy

In [59]:
#hasdebt

df['Has_Debt'] = df['Has_Debt'].fillna('Yes')
df

,Name,Age,Gender,Income,City,Has_Debt,Debt_Amount,name
0,Alice,25.0,Female,50000.000000,New York,Yes,15000.0,Alice
1,Bob,32.0,Male,60000.000000,Los Angeles,No,0.0,Bob
2,Charlie,31.0,Male,55000.000000,New York,Yes,12000.0,Charlie
3,Unknown,45.0,male,45000.000000,Chicago,No,0.0,Unknown
4,Eve,29.0,Male,54666.666667,Los Angeles,Yes,18000.0,Eve
5,Frank,34.0,female,70000.000000,Los Angeles,Yes,20000.0,Frank
6,Grace,31.0,Female,52000.000000,Chicago,No,0.0,Grace
7,Heidi,41.0,Male,48000.000000,New York,Yes,14000.0,Heidi
8,Ivan,30.0,Male,62000.000000,Chicago,Yes,NaN,Ivan
9,Judy,27.0,Female,50000.000000,Chicago,No,0.0,Judy

In [60]:
#debt amount

df['Debt_Amount'] = df['Debt_Amount'].fillna('0')
df

,Name,Age,Gender,Income,City,Has_Debt,Debt_Amount,name
0,Alice,25.0,Female,50000.000000,New York,Yes,15000.0,Alice
1,Bob,32.0,Male,60000.000000,Los Angeles,No,0.0,Bob
2,Charlie,31.0,Male,55000.000000,New York,Yes,12000.0,Charlie
3,Unknown,45.0,male,45000.000000,Chicago,No,0.0,Unknown
4,Eve,29.0,Male,54666.666667,Los Angeles,Yes,18000.0,Eve
5,Frank,34.0,female,70000.000000,Los Angeles,Yes,20000.0,Frank
6,Grace,31.0,Female,52000.000000,Chicago,No,0.0,Grace
7,Heidi,41.0,Male,48000.000000,New York,Yes,14000.0,Heidi
8,Ivan,30.0,Male,62000.000000,Chicago,Yes,0,Ivan
9,Judy,27.0,Female,50000.000000,Chicago,No,0.0,Judy

In [61]:
df.isnull().sum()

Name           0
Age            0
Gender         0
Income         0
City           0
Has_Debt       0
Debt_Amount    0
name           0
dtype: int64